apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:open-cluster-management:spokecluster-admission
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:open-cluster-management:spokecluster-admission
subjects:
  - kind: ServiceAccount
    name: spokecluster-admission-sa
    namespace: open-cluster-management
