apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:open-cluster-management:spokecluster:{{ .SpokeClusterName }}
rules:
# Allow spoke agent to rotate its certificate
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests/spokeclusteragent"]
  verbs: ["create"]
# Allow spoke agent to get/list/watch its owner spoke cluster
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["spokeclusters"]
  resourceNames: ["{{ .SpokeClusterName }}"]
  verbs: ["get", "list", "watch"]
# Allow spoke agent to update the status of its owner spoke cluster
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["spokeclusters/status"]
  resourceNames: ["{{ .SpokeClusterName }}"]
  verbs: ["patch", "update"]
